### ISSUE TITLE
Allow external processing

### ISSUE THREAD

**Issue by olantrust** [janis91/ocr#28] opened 2016-11-12 18:01 UTC
It would be useful to have the ability for the app to use instances of the required dependencies:
a) OCRmyPDF
b) tesseract-ocr
Present at an external site, if this is possible.
This would benefit those using hosted Nextcloud versions where they cannot control the software on the server.

**Comment by janis91** [comment] 2016-11-13 22:43
That's actually a pretty interesting idea! I will have a look into this soon. Thx!

**Comment by janis91** [comment] 2016-11-14 12:37
@olantrust the problem is, that there are no official docker containers with a REST API available yet.

Maybe i will try to build something up in a separate project to get this going... Then there might be something like this: [https://github.com/tleyden/open-ocr](https://github.com/tleyden/open-ocr)

I did not do anything with Docker yet, so it could be a little bit challenging.

If you know anything other, could you please leave me a comment?

The next problem might be the load... The files would not stay locally on the file / nextcloud server. Instead they would have to be transferred to the processing machine and the results back to the API of Nextcloud.

This would produce a large amount of network load.

What do you think about this?

- janis

**Comment by janis91** [comment] 2016-12-29 19:58
closed as there is no good solution for this yet.

**Closed by janis91** 2016-12-29 19:58 UTC
Labels: enhancement, feature
