### ISSUE TITLE
After update to 4.4.1 OCR does not work due incorrect language settings

### ISSUE THREAD

**Issue by ratermir** [janis91/ocr#224] opened 2019-09-14 10:59 UTC
After some time (maybe 2 months) I updated OCR application to the version 4.4.1 and since then it does not work. Every access to “files” application and also to the setup page shows the message on top of the page:

OCR: An unexpected error occured during load of your favorite languages. Please try again.

When I tried to access OCR setup as an admin, I see only page title () and the rest is empty - I don’t see any options there (only rotating circle that means “I am working”).

The behaviour is the same also in current version (4.4.3). 
Before this update, OCR worked well.
I don’t remenger the previous version. Language settings (if I remember it correctly) were “czech”, “german”, “english” and “spanish”.

I was looking for some configuration (either on filesystem or in database) to delete it - i supposed that it creates new one, but didn't find any.

Nextcloud 16.0.3 docker php-fpm mysql, current OCR verssion 4.4.3 (ocurred in 4.4.1)

**Comment by janis91** [comment] 2019-09-16 18:58
Could you please look into your browser's console and even into your borwser's network log and search for errors and especially for `languages`(like in the example picture below) in the network tab. If this is not successful, I need even more information. If it's too sensible (like the full URL), you could send me the informaiton by email as well. I will try to figure out, what's failing then.

<img width="1199" alt="Bildschirmfoto 2019-09-16 um 20 54 16" src="https://user-images.githubusercontent.com/20393872/64985090-61f2c300-d8c4-11e9-8709-7aaa6ecc7e2b.png">

**Comment by ratermir** [comment] 2019-09-17 07:56
In the log I found this message:
![image](https://user-images.githubusercontent.com/52619304/65022071-9734fa80-d930-11e9-834a-b2501943cda7.png)
but since the "js" is minified, I didn't find anything there. 

In the network log I found this:
![image](https://user-images.githubusercontent.com/52619304/65022436-4f62a300-d931-11e9-9641-50aa1b8e308b.png)


![image](https://user-images.githubusercontent.com/52619304/65022472-5ab5ce80-d931-11e9-83a6-a1c6249d974c.png)

**Comment by ratermir** [comment] 2019-10-01 08:48
@janis91 I am not aware that I have closed this problem, but it seems to be. However this issue still persists. Please could you tell me where the language configuration is stored and how can I clear / reset it?

**Comment by sl060270** [comment] 2019-10-14 08:38
![Nextcloud_OCR](https://user-images.githubusercontent.com/23502080/66738326-7cda3800-ee6e-11e9-8d49-423c36bd6cd8.jpg)

I have the same problem. Let me know how I can support ...

**Comment by MarcReckel** [comment] 2019-11-08 15:02
![language](https://user-images.githubusercontent.com/35332418/68483143-4c05dc80-023b-11ea-913d-d26361747ed0.jpg)

Same Problem for me as well. i only tried using the app since 4.4.15 but same for 4.4.16
Nextcloud 17.0 hosted by hetzner.
I mosly use firefox as browser on my workcomputer but didn't work with firefox or opera at home either.

**Comment by reavessm** [comment] 2020-01-20 16:04
I'm on Nextcloud 18, and OCR 4.4.33, and the problem still exists.

**Comment by janis91** [comment] 2020-01-20 16:10
@reavessm NC 18 is not supported, yet at least. But with v 4.5 the problem should be gone. I setup a new nextcloud server with an additional app directory just to test it.

**Comment by ratermir** [comment] 2020-01-25 10:22
OCR Version 5.0.5, NC 17.0.1, the issue still persists.
Error message in the "Files" has disappeared,  but in the config I can't navigate to the OCR config and OCR menu don't show in the file menu. 

![image](https://user-images.githubusercontent.com/52619304/73119618-b558da00-3f64-11ea-82af-4893787a6d92.png)

**Comment by janis91** [comment] 2020-01-25 14:30
I will look into it tomorrow. I reopen the issue therefore

**Comment by janis91** [comment] 2020-01-26 18:04
@ratermir Can you maybe look into the browsers console and network tab again, what does it say now, because normally the bug should be fixed.. At least I cannot reproduce this..

**Comment by ratermir** [comment] 2020-01-26 19:57
There is nothing about language in the console, only an error about some icon.
![image](https://user-images.githubusercontent.com/52619304/73140888-204a0400-407e-11ea-9272-84a95b902846.png)

I am adding full console log (cought until the "running image apears) and the network log in HAR format. Perhaps it helps.
[cloud.anirad.cz-1580067752639.log](https://github.com/janis91/ocr/files/4114264/cloud.anirad.cz-1580067752639.log)

[cloud.anirad.cz.har.zip](https://github.com/janis91/ocr/files/4114265/cloud.anirad.cz.har.zip)

**Comment by ratermir** [comment] 2020-01-26 20:12
the quality of the picture wad bad, so once again:
![image](https://user-images.githubusercontent.com/52619304/73141112-918ab680-4080-11ea-9f8f-91db3a2d8464.png)

**Comment by janis91** [comment] 2020-01-26 20:58
@ratermir Thanks for attaching. Unfortunately I cannot identify the cause. But what I can see from your screenshot and cannot find actually in the log file is the `Uncaught r` line (3rd line). This is really interesting. The app_dark.svg Content Security Policy error shouldn't be related to the behavior.

**Comment by HelpfulRock** [comment] 2020-01-28 14:40
for me the Problem is solved - menu looks like in the photos and loads pretty fast. I'm not happy yet with the size of the OCR since the document i used it on exploded from 834kb to 5,5mb but looking at #251 it looks like this is expected.

**Comment by janis91** [comment] 2020-02-01 08:41
@ratermir do you have more information on this, because I cannot identify any problem with ANY setup I can imagine and try locally. I will close this as long as there is no more information.

**Comment by ratermir** [comment] 2020-02-02 14:40
Hi Janis
Sorry for delay, I have no time to work on it continuopusly.  I wanted to offer you to create virtual host with my installation of nextcloud and provide you access there to test / develop it. But it consumes a time. 
I have no better idea how to manage to repeat this issue on another environment.

**Comment by janis91** [comment] 2020-02-02 15:35
That‘d be perfect. Atm I don‘t have another idea.

**Comment by ratermir** [comment] 2020-02-02 18:45
@janis91 
I have prepared environment for testing, can you give me your mail - I'll send how to connect there.

**Comment by janis91** [comment] 2020-02-02 21:50
> @janis91
> I have prepared environment for testing, can you give me your mail - I'll send how to connect there.

It‘s on my github profile ;-)

**Comment by ratermir** [comment] 2020-02-06 22:19
@janis91
I've sent you info how to connect by mail. The VM will be active till end of February.

**Comment by janis91** [comment] 2020-02-07 10:01
I‘ll look at it this weekend. Thank you for your effort!

**Comment by janis91** [comment] 2020-02-08 22:50
@ratermir Ok. The first thing that I see is the following error when trying to load Ocr into Namespace the following error is thrown:

```
Error: Template was precompiled with a newer version of Handlebars than the current runtime. Please update your runtime to a newer version (>= 4.3.0). exception.js:50:22
    checkRevision runtime.js:39
    template runtime.js:57
    template handlebars.runtime.js:51
    <anonymous> settings.js:1
    n settings.js:1
    <anonymous> settings.js:1
    n settings.js:1
    <anonymous> settings.js:1
    <anonymous> settings.js:1
    <anonymous> settings.js:1
    <anonymous> settings.js:1
```

I would guess, that the Handlebars engine provided by Nextcloud on your specific installation is not matching the required version. The ocr app is requiring a version >=4.3.0.

My first suggestion is, that you wait for v6.0.0 of ocr. It should be available soon and does not depend on any Nextcloud specific vendor library. Unfortunately, a downside in the first time will be, that it won't support PDF files for scanning anymore. But I work on a solution.

Thank You for your patience :-)

**Closed by janis91** 2020-02-08 22:50 UTC
Labels: bug

**Comment by ratermir** [comment] 2020-02-09 18:36
Ok, I'll wait, I can survive without it :) Thanks a lot for investigation. 
But it is a crazy issue - becuse I didn't do any special tasks or installations. I only installed and updated plugins standard way (and uninstall somthing), and performed updates of nectcloud (since NC 14, which was my first installation). So it must be plugins incomaptibility or something like this.

**Comment by janis91** [comment] 2020-02-09 21:25
Yes. It might be even my fault, because I updated handlebars under the hood. But still strange, that it works for me :-D
