### ISSUE TITLE
I can't get ocr working

### ISSUE THREAD

**Issue by quelo1972** [janis91/ocr#157] opened 2018-04-24 12:12 UTC
I have an ubuntu-server 16.04 LTS with nextcloud 13 installed and working
I followed instructions from [https://github.com/janis91/ocr/wiki/Installation-and-Configuration-(Docker-setup)](url) to install OCR support, by the commands below

in redis directory
`docker build --build-arg PASSWORD="***************" -t andrea/redis .`
in worker directory
```
docker build --build-arg LANGUAGES="tesseract-ocr-ita" -t andrea/ocr .
docker network create --driver bridge isolated_ocr
docker run --name redis --network=isolated_ocr -p 6379:6379 -d andrea/redis
docker run --name ocr --network=isolated_ocr -e "NODE_ENV=production" -e "REDIS_HOST=redis" -e "REDIS_PORT=6379" -e "REDIS_DB=0" -v /home/ncdata:/home/node/data:ro -v /home/nctmp:/home/node/output -d andrea/ocr
```
I've configured the app in nextcloud as below
![cattura](https://user-images.githubusercontent.com/28729838/39185959-4066f4e6-47c9-11e8-84cb-7538c7c29d3a.PNG)

I expect that running ocr command in nextcloud over a pdf file i will obtain a text file, instead a temp file of 0 kb is created in the temp directory and the ocr process will not terminate.
In the log of the ocr docker container i have the errors and warning below

`
2018-04-24T11:37:26.384Z - error: ERROR: NOAUTH Authentication required..,
2018-04-24T11:37:26.385Z - warn: Connection closed to redis server.,
2018-04-24T11:37:28.389Z - error: ERROR: NOAUTH Authentication required..,
2018-04-24T11:37:28.389Z - warn: Connection closed to redis server.,
2018-04-24T12:06:59.661Z - warn: Connection closed to redis server.,
2018-04-24T12:06:59.661Z - error: ERROR: NOAUTH Authentication required..`

**Comment by janis91** [comment] 2018-04-24 16:34
I saw that I did forget to document the REDIS_PASSWORD setting for the run command of the worker docker container. Please read the documentation for this step again and repeat the step. I apologise for that mistake. Now it should work. And thank you for figuring this out. And giving more precise input.

**Comment by quelo1972** [comment] 2018-04-24 18:26
@janis91 
Ok!
Folowed new instructions and executed this command for tue run worker:

`docker run --name ocr --network=isolated_ocr -e "NODE_ENV=production" -e "REDIS_PASSWORD=R3d1sPaSsw07d" -e "REDIS_HOST=redis" -e "REDIS_PORT=6379" -e "REDIS_DB=0" -v /home/ncdata:/home/node/data:ro -v /home/nctmp:/home/node/output -d andrea/ocr`

but now I have the error below:
![cattura](https://user-images.githubusercontent.com/28729838/39206432-b3ea6f9a-47fd-11e8-9251-fb037bb57fd3.PNG)

**Comment by janis91** [comment] 2018-04-24 19:39
Ok, we are one step further then :-) I guess this is something other users faced as well and actually I am currently not quite sure what the reason for this is. Therefore I can only ask for patience and I hope that I can fix this soon. I have to reproduce this on another machine and figure out whats the reason for the "File not found" Error. I guess it has something to do with the mapping of the nc data folder into the docker container on home/node/data . One thing that comes to my mind is, can you check if there is such a structure available in your ncdata folder: "amministratore/files/Nextcloud Manual.pdf"?

**Comment by quelo1972** [comment] 2018-04-24 20:26
In the host filesystem I have this:
```
root@CLOUD01:/home/ncdata/amministratore/files# ls -la
totale 4648
drwxr-xr-x 4 www-data www-data    4096 apr 23 18:51 .
drwxr-xr-x 4 www-data www-data    4096 apr 20 16:59 ..
drwxr-xr-x 2 www-data www-data    4096 apr 20 14:09 Documents
-rw-r--r-- 1 www-data www-data   12323 apr 23 18:51 New Document.docx
-rw-r--r-- 1 www-data www-data 4247330 apr 20 14:09 Nextcloud Manual.pdf
-rw-r--r-- 1 www-data www-data  462413 apr 20 14:09 Nextcloud.mp4
drwxr-xr-x 2 www-data www-data    4096 apr 23 18:51 Photos
-rw-r--r-- 1 www-data www-data   12323 apr 23 18:36 prova.odt
```
In the docker container I have this:
```
root@b7a448d80310:/home/node/data/amministratore/files# ls -la
total 4648
drwxr-xr-x 4 www-data www-data    4096 Apr 23 16:51 .
drwxr-xr-x 4 www-data www-data    4096 Apr 20 14:59 ..
drwxr-xr-x 2 www-data www-data    4096 Apr 20 12:09 Documents
-rw-r--r-- 1 www-data www-data   12323 Apr 23 16:51 New Document.docx
-rw-r--r-- 1 www-data www-data 4247330 Apr 20 12:09 Nextcloud Manual.pdf
-rw-r--r-- 1 www-data www-data  462413 Apr 20 12:09 Nextcloud.mp4
drwxr-xr-x 2 www-data www-data    4096 Apr 23 16:51 Photos
-rw-r--r-- 1 www-data www-data   12323 Apr 23 16:36 prova.odt
```

**Comment by quelo1972** [comment] 2018-05-06 15:32
I've tried to execute ocrmypdf insede the container but I get an error read-only filesystem, see below
![cattura](https://user-images.githubusercontent.com/28729838/39674877-43522f5c-5153-11e8-89e6-314b48cda305.PNG)
How can I solve this issue?

**Comment by quelo1972** [comment] 2018-05-06 15:38
Also tried to simply create an empty file in /home/node/data/andrea.rossetti/files with the command touch but I get the same error, see below
![cattura](https://user-images.githubusercontent.com/28729838/39674950-34995e6c-5154-11e8-8929-8cd8ded223e9.PNG)

**Comment by Happyfeet01** [comment] 2018-05-06 15:42
No issues like this...

I try to execute the same command and it works. But get this message. 

```
node@7d720e0e52dc:~/data/files$ ocrmypdf -l deu --force-ocr Clatronic_user_manual_MWG_775_H.pdf Clatronic.pdf

WARNING -   64: page has no images - all vector content will be rasterized at 400 DPI, losing some resolution and likely increasing file size. Use --oversample to adjust the DPI.
```

**Comment by Happyfeet01** [comment] 2018-05-22 19:52
Gibt's ne Info darüber wie man den Fehler beheben kann? @janis91

**Comment by quelo1972** [comment] 2018-05-22 20:21
I translate in english... Is there any information about how to fix the error?

**Comment by janis91** [comment] 2018-05-24 14:38
Not yet. Sorry, I am quite busy currently. Actually I hope I can do something on next weekend, but I am not sure yet.

**Comment by janis91** [comment] 2018-05-26 12:06
@Happyfeet01 @quelo1972 Did you try to use:
```docker run --name ocr --network=isolated_ocr -e "NODE_ENV=production" -e "REDIS_PASSWORD=+++++++++++" -e "REDIS_HOST=redis" -e "REDIS_PORT=6379" -e "REDIS_DB=0" -v /home/ncdata:/home/node/data -v /home/nctmp:/home/node/output -d andrea/ocr``` (without :ro behind the data dir). just too make sure that it's not caused by the "read-only" flag. Another guess is, that your docker user has not even the permission to read the files on your host. Which OS are you using? Maybe this fix helps: https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker

Because all I do on my debian host is following the how to and it works.. So I cannot reproduce this.

**Comment by Happyfeet01** [comment] 2018-05-26 14:49
Yes tried this without :ro but the same error.

**Comment by quelo1972** [comment] 2018-05-26 20:44
@janis91 
I use Ubuntu 18.04

**Comment by Happyfeet01** [comment] 2018-06-24 19:14
Any new Updates?

**Comment by janis91** [comment] 2019-05-26 15:52
I won't support anything prior version 4, because the whole setup is just too much effort. I will close this issue now and hope that version 4 (which will be shipped in a few weeks probably) will fill your need. If not. please feel free to fork the repo and work on the old code base which will reside in the branch "not-maintained".

**Closed by janis91** 2019-05-26 15:52 UTC
