### ISSUE TITLE
Spaces and new lines not in OCR

### ISSUE THREAD

**Issue by TheEagle13** [janis91/ocr#201] opened 2019-07-09 17:35 UTC
Hello, first off, thank you SO MUCH for your work on this. this has mad my life so much easier.

However when doing the OCR I've found that the process doesn't add spaces and new lines. 
When  I copy and paste into a text document, everything is squished together without spaces or new lines.

# Bug report / Feature request
## Expected Behavior
A Copy and Paste from the OCR'd document should mimic the image, IE spaces in between words, and new lines where paragraph breaks are.

## Current Behavior
a copy and paste has no new lines or spaces, everything is one giant run on word.

## Context
If needing to copy parts of a PDF document into an email, but not the whole thing, it would be nice to have spaces in between the words.

## Your Environment

* OCR version used: 4.2.11
* Browser Name and version: Chrome 75.0.3770.100
* Operating System and version (desktop or mobile): Windows 10 Desktop
* ownCloud/nextcloud version: 16.0.3
* PHP version Unsure 
* Database version: MariaDB 10.4.6
* Are you using encryption: no

**Comment by janis91** [comment] 2019-07-10 07:18
First of all, thank you for your warm words.

I can't completely reproduce this without having the actual original image available.

When I test the ocr during development, I use this image: https://github.com/naptha/tesseract.js/blob/master/tests/assets/images/testocr.png

When executing within nextcloud and downloading the pdf file, I get the following output from copying the content of the pdf:
```text
 This is a lot of 12 point text to test the ocrcodeandseeifitworkson alltypes offile format.
The quick brown dog jumped over the
lazy fox. The quick brown dog jumped over the lazy fox. The quick brown dog
jumpedoverthe lazyfox.Thequick brown dog jumped overthe lazy fox.
```

if I use the https://github.com/tesseract-ocr/tesseract command line tool to process the same image and returning it as pdf file, I get the following:

```text
 This is a lot of 12 point text to test the ocrcodeandseeifitworkson alltypes offile format.
The quick brown dog jumped overthe
lazy fox. The quick brown dog jumped over the lazy fox. The quick brown dog
jumpedoverthe lazyfox.Thequick brown dogjumpedoverthe lazyfox.
```

So obviously tesseract itself seems to have some problems with adding text to pdf here (https://github.com/tesseract-ocr/tesseract/issues/2127). Maybe this will get better with newer versions, but I'm not sure if I can do something here. 
In general the quality of the output pdf strongly depends on the input image's quality.

Moreover, for me it seems to depend on the pdf viewer you use. The results I've shown above are copied from the "Preview" app in Mac OS. If I use Adobe Acrobat Reader DC, I can strongly improve the result when copying from both outputs, I get the following:

```text
This is a lot of 12 point text to test the
ocr code and see if it works on all types
offile format.
The quick brown dog jumped over the
lazy fox. The quick brown dog jumped
over the lazy fox. The quick brown dog
jumped over the lazy fox. The quick
brown dog jumped over the lazy fox.
```

If I use the builtin pdf viewer for nextcloud, which is based on pdf.js, if I know it right, I get the following:

```text
This
is 
a 
lot 
of 
12 
point
text
to 
test
the
ocr 
code
and
see
if 
it 
works
on 
all 
types
of
file
format.
The
quick
brown
dog 
jumped
over
the
lazy
fox. 
The
quick
brown
dog 
jumped
over
the 
lazy
fox.
The
quick
brown
dog
jumped
over
the
lazy
fox.
The
quick
brown
dog 
jumped
over
the
lazy
fox.
```
(I am not joking)

So one approach could be to try another reader/viewer and another one is to use an input image with higher quality. 
I will close this issue for now, because this is definitely an issue of the tesseract engine itself AND how viewers/readers interpret the output of it.

Would it make sense to you, to get the output as plain text file instead or do you still prefer the pdf output?
Because the plain text mode is way more stable than the pdf output mode.

In general the text layer in the resulting pdf is good for searching but not that good for copy&paste I would sum up.

**Closed by janis91** 2019-07-10 07:18 UTC

**Comment by TheEagle13** [comment] 2019-07-10 12:24
Thank you for that. I should have done a little more testing on my side, but I didn't realize that different readers have different effects on it. It appears that most of my issues stem from most of my scans being receipts, bit I also see the difference between readers now. 

By all means, I prefer the PDF Overlay output that you have now. This is EXACTLY the thing I've been wanting, and I couldn't find an easy solution to achieve it until now. All the other solutions I've tried just output to a txt file, and then it becomes a hassle of correlation and other issues for me. So, thank you again very much for making this, and thanks for your time troubleshooting this with me.

**Comment by janis91** [comment] 2019-07-10 12:39
> Thank you for that. I should have done a little more testing on my side, but I didn't realize that different readers have different effects on it. It appears that most of my issues stem from most of my scans being receipts, bit I also see the difference between readers now.
> 
> By all means, I prefer the PDF Overlay output that you have now. This is EXACTLY the thing I've been wanting, and I couldn't find an easy solution to achieve it until now. All the other solutions I've tried just output to a txt file, and then it becomes a hassle of correlation and other issues for me. So, thank you again very much for making this, and thanks for your time troubleshooting this with me.

You're welcome :-)
