### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by mokkin** [janis91/ocr#246] opened 2020-01-23 00:57 UTC
I have a fresh test install of ocr, but even with my first attempts I get this error:
```
GEThttp://betacloud.test.de/apps/ocr/img/icon/ocr.svg
[HTTP/1.1 200 OK 43ms]

The escapeHTML library is deprecated! It will be removed in nextcloud 19. 2 globals.js:26:15
GEThttp://betacloud.test.de/apps/ocr/vendor/pdf.js/pdf.worker.min.js?v=623b4bda-0
[HTTP/1.1 200 OK 2292ms]

An error occured in OCR. r: "Ein unerwarteter Fehler trat beim Verarbeiten der PDF auf."
    n http://betacloud.test.de/apps/ocr/js/app.js?v=623b4bda-0:1
    r http://betacloud.test.de/apps/ocr/js/app.js?v=623b4bda-0:1
    getDocumentPagesAsScaledImages http://betacloud.test.de/apps/ocr/js/app.js?v=623b4bda-0:1
    c http://betacloud.test.de/apps/ocr/js/app.js?v=623b4bda-0:1
 
Exception
​
columnNumber: 0
​
data: null
​
filename: "http://betacloud.test.de/apps/ocr/vendor/pdf.js/pdf.min.js?v=623b4bda-0"
​
lineNumber: 1
​
message: ""
​
name: "NS_ERROR_FAILURE"
​
result: 2147500037
​
stack: "beginDrawing@http://betacloud.test.de/apps/ocr/vendor/pdf.js/pdf.min.js?v=623b4bda-0:1:247050\ninitializeGraphics@http://betacloud.test.de/apps/ocr/vendor/pdf.js/pdf.min.js?v=623b4bda-0:1:70486\nrender/<@http://betacloud.test.de/apps/ocr/vendor/pdf.js/pdf.min.js?v=623b4bda-0:1:52012\n"
​
<prototype>: ExceptionPrototype { toString: toString(), name: Getter, message: Getter, … }
app.js:1:27549
    clickOnProcessButtonEvent http://betacloud.test.de/apps/ocr/js/app.js?v=623b4bda-0:1
    c http://betacloud.test.de/apps/ocr/js/app.js?v=623b4bda-0:1
```
Any idea why?

**Comment by janis91** [comment] 2020-01-23 06:01
Seems like a problem with drawing the pdf. Did you try another document or image yet? I can‘t say if the error is strongly bound to that one doc or if it is a general problem. If other files cause the same error: can you provide Nextcloud version and installed apps?

**Comment by janis91** [comment] 2020-01-23 10:44
It's very likely, that this is caused by the pdf that should be processed:
https://github.com/mozilla/pdf.js/issues/6741
I will close this issue, because I can't say/do anything about this.

**Closed by janis91** 2020-01-23 10:44 UTC
Labels: help wanted

**Comment by mokkin** [comment] 2020-01-23 16:36
Probably it was my browser plugin uMatrix blocking content from external sources. After I deactivated it, it took a download from https://raw.githubusercontent.com which is part of the ocr app.
```
grep -r -l 'githubusercontent' *
appinfo/info.xml
```

Maybe this can be included?

**Comment by janis91** [comment] 2020-01-23 18:27
That issue should be gone now. The tessdata will no longer be downloaded from github. It gets installed from v5.0.3 up automatically.
