### ISSUE TITLE
Bug Report: Problem with multiple page documents

### ISSUE THREAD

**Issue by ehcatl** [janis91/ocr#212] opened 2019-08-08 02:48 UTC
When processing multiple page PDF documents, the process stays idle for hours. I split the file into eleven pages and processed them without a problem. 
¿Should I install some other software on the computer?

**Comment by janis91** [comment] 2019-08-09 14:15
Can you give more information on this? Like for example the browser you use and which version etc..
I don't want to sound rude, but for this purpose I setup an issue template:
There is much more information needed for me than just "multi page PDF". Also the number of pages and different browsers or even the document itself (if it's safe to share it with me) are very important to figure out what happened (AND if it's maybe expected behavior, because some big documents really take very long). Could you provide this information please? Otherwise I'll have to close this issue, because I test already with a 14 page PDF and for me it works on several browsers (some may take a little longer than Chrome for example).

**Comment by dst21** [comment] 2019-09-16 07:02
I have the same issue within two Nextclouds (version 16.0.3 and 16.0.4). Browser: Google Crome, version 77.0.3865.75 and Mozilla Firefox, version 69. Tested with a PDF with 16 sites. I will send you one of my testfiles by email.

**Comment by janis91** [comment] 2019-09-16 18:51
@dst21 Thank you for your example you sent by email. I can reproduce the error and will have a closer look. Unfortunately I could not identify the root cause yet. I will try as soon as I can :-)

**Comment by itsChris** [comment] 2019-10-01 08:37
hi janis - i do have the same problem. i can send you the files per email. i'm on nextcloud 16.0.5 with Firefox 69.0.1 (64-Bit). multiple single page documents work, but none of the multipage documents do..

as an example i tried it with the Nextcloud Manual.pdf.. 

cheers

Christian

**Comment by dst21** [comment] 2019-11-05 13:31
I have found out, that at the beginnig of the ocr task, my cpu is working and this task takes some ram (google chrome task). after about a minute, the cpu is no longer busy, but ram is still in use. 

i think, this browser task is dying after some time.

Processing two pdfs with two pages each ist still working fine (takes about one minute).

I have also watched into the chrome dev tools and found this in Console: 

`Uncaught (in promise) TypeError: Cannot read property 'postMessage' of null at index.js:179
`

**Closed** 2020-01-21 13:19 UTC
Labels: bug
