### ISSUE TITLE
NC 12/OCR 3.0.0-beta.7 Cannot enable app

### ISSUE THREAD

**Issue by curtisolson** [janis91/ocr#101] opened 2017-07-07 01:28 UTC
I went through the installation and setup instructions. The "Enable" button is greyed out and there is a "Remove" button to the left. I'm sure it has something to do with my set-up, but I'm not sure where to start with the debugging. I didn't see anything in the admin logs. 

I did just see the note that it's Linux only. I'm on OSX, so I'm hoping that is enough *nix to work. 

![screen shot 2017-07-06 at 6 21 38 pm](https://user-images.githubusercontent.com/2302973/27939198-099a183a-6278-11e7-987b-13ca01316a9d.png)

## Your Environment

* OCR version used: 3.0.0-beta.7
* Browser Name and version: Chrome, but shouldn't matter.
* Operating System and version (desktop or mobile): OSX
* ownCloud/nextcloud version: 12.0
* PHP version: 5.5.38
* Database version: Default sqllite (should be curent)
* Are you using encryption: no

## Log File Content (nextcloud/owncloud.log of the "data"-directory)
The only thing in the log file is this error on the logo. It shows up repeatedly.

{"reqId":"exogEiUneNqm4HVL70Pb","level":3,"time":"2017-07-07T01:26:03+00:00","remoteAddr":"::1","user":"DevOps","app":"no app in context","method":"GET","url":"\/data\/.ocdata?t=1499390763206","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"theming.Theming.getLogo\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/Users\\\/curtis\\\/Documents\\\/code\\\/ph-secure-site\\\/lib\\\/private\\\/Route\\\/Router.php(339): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('theming.Theming...', Array, 1)\\n#1 \\\/Users\\\/curtis\\\/Documents\\\/code\\\/ph-secure-site\\\/lib\\\/private\\\/URLGenerator.php(70): OC\\\\Route\\\\Router->generate('theming.Theming...', Array)\\n#2 \\\/Users\\\/curtis\\\/Documents\\\/code\\\/ph-secure-site\\\/apps\\\/theming\\\/lib\\\/ThemingDefaults.php(156): OC\\\\URLGenerator->linkToRoute('theming.Theming...')\\n#3 \\\/Users\\\/curtis\\\/Documents\\\/code\\\/ph-secure-site\\\/lib\\\/public\\\/Defaults.php(186): OCA\\\\Theming\\\\ThemingDefaults->getLogo(true)\\n#4 \\\/Users\\\/curtis\\\/Documents\\\/code\\\/ph-secure-site\\\/core\\\/templates\\\/layout.guest.php(45): OCP\\\\Defaults->getLogo()\\n#5 \\\/Users\\\/curtis\\\/Documents\\\/code\\\/ph-secure-site\\\/lib\\\/private\\\/Template\\\/Base.php(176): include('\\\/Users\\\/curtis\\\/D...')\\n#6 \\\/Users\\\/curtis\\\/Documents\\\/code\\\/ph-secure-site\\\/lib\\\/private\\\/Template\\\/Base.php(151): OC\\\\Template\\\\Base->load('\\\/Users\\\/curtis\\\/D...', NULL)\\n#7 \\\/Users\\\/curtis\\\/Documents\\\/code\\\/ph-secure-site\\\/lib\\\/private\\\/legacy\\\/template.php(202): OC\\\\Template\\\\Base->fetchPage(NULL)\\n#8 \\\/Users\\\/curtis\\\/Documents\\\/code\\\/ph-secure-site\\\/lib\\\/private\\\/legacy\\\/template.php(224): OC_Template->fetchPage()\\n#9 \\\/Users\\\/curtis\\\/Documents\\\/code\\\/ph-secure-site\\\/lib\\\/private\\\/Template\\\/Base.php(132): OC_Template->fetchPage()\\n#10 \\\/Users\\\/curtis\\\/Documents\\\/code\\\/ph-secure-site\\\/core\\\/templates\\\/403.php(7): OC\\\\Template\\\\Base->printPage()\\n#11 {main}\",\"File\":\"\\\/Users\\\/curtis\\\/Documents\\\/code\\\/ph-secure-site\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":130}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/60.0.3112.40 Safari\/537.36","version":"12.0.0.29"}

**Comment by janis91** [comment] 2017-07-07 05:35
Hi I guess that this logo error message is a general error and not caused by the OCR app, as far as I understand the app is not enabled.. It cannot cause errors then. One thing that comes up to my mind is: Do you have php-redis installed AND activated? I don't know why NC12 did change the behavior for enabling apps. Because with NC11 it showed always an error message what might be missing so I can just guess. If this the case it could also be OSX (I think NC in general doesn't support OSX officially). Hope that helps.

**Comment by janis91** [comment] 2017-07-14 08:58
Did you test it because I tried to reproduce this issue and couldn't. I will close this for now. You can still mention me with new details, then I will reopen it. Thanks!

**Closed by janis91** 2017-07-14 08:58 UTC

**Comment by curtisolson** [comment] 2017-07-14 15:36
I haven’t yet, but I think it might be that my mac’s php does not match the
dependencies. I’m blocked on upgrading for another week, but will test out
then.


On July 14, 2017 at 1:58:36 AM, Janis Koehr (notifications@github.com)
wrote:

Did you test it because I tried to reproduce this issue and couldn't. I
will close this for now. You can still mention me with new details, then I
will reopen it. Thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/janis91/ocr/issues/101#issuecomment-315308992>, or mute
the thread

**Comment by danielepercivaldi** [comment] 2018-02-06 23:47
Same issue here:
Ubuntu 16.04
Apache 2.4.18
Php 7.0.22
NC 12.0.5
Ocr 3.2.0

All is ok with docker images build. Containers are running good. App appears in disabled apps but enable button is greyed.
