### ISSUE TITLE
OCR: 1 datei in der Warteschlange.

### ISSUE THREAD

**Issue by gituser10173** [janis91/ocr#130] opened 2017-12-22 16:24 UTC
Second Trial in a better reading way

# Bug report / Feature request
## Current Behavior

Dear Janis,
I wan't that after use the function "Texterkennung" inside the nextcloud web page, that after processing i have a OCR-PDF in the same directory the original file is (JPG or PDF).
## Possible Solution

Dear Janis,
after trying your app i have some trouble to use this in the right way. I think that i made something wrong. Now after the second day of raeding and trying - i would like to ask you it you have an ideam what I can do.

Docker + Redis - I have no experience with that two things but I'm interresting in.
For Redis i have read some (like wikipedia and also the admin manual from nextcloud).

For Docker i have read on docker the "beginners" manusl and now understand better (but i think not deep enough).

But i would like to give me a chance to use your OCR App inside my nextcloud. I would take there invoices inside the nextcloud (only private stuff). The source for the invoices are sometimes my scanner.

Many thanks and best regards,

And now the description:

Inside the nextcloud web page i use the function "Texterkennung".
After this a job info is pendig on top on nextcloud web access.

The LOG from nextcloud has the following new lines:
Debug | no app in context | Retrieved the following array from Redis: [] | 2017-12-22T16:16:48+0100
-- | -- | -- | --
Debug | no app in context | Following jobs failed: [] | 2017-12-22T16:16:43+0100
Debug | no app in context | Check if files were processed by ocr and if so, put them to the right dirs. | 2017-12-22T16:16:43+0100

## Steps to Reproduce (for bugs)

config.php
$CONFIG = array (
  'instanceid' => 'ocev1lqkpk9c',
  'passwordsalt' => 'zLnapHvJjICwR58kZtOSE9RDYGrkUp',
  'secret' => '1qlfJOyUAR5DUfHJpW6YhK6cvsHT5Bd+brZ7YUJc8bysh2/p',
  'trusted_domains' =>
  array (
    0 => 'nextcloud.trupletz.local',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'overwrite.cli.url' => 'http://nextcloud.trupletz.local/nextcloud',
  'dbtype' => 'mysql',
  'version' => '12.0.4.3',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost:5432',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_pcadmin',
  'dbpassword' => 'IzHc6CiRZ/bXtwYTjr2T7Z7eLGd7/S',
  'installed' => true,
  'tempdirectory' => '/home/pcadmin/nextcloudtemp',
  'loglevel' => 0,
);

+ Nextcloud benötigte Pakete
  sudo apt-get install apache2 mariadb-server libapache2-mod-php7.0
  sudo apt-get install php7.0-gd php7.0-json php7.0-mysql php7.0-curl php7.0-mbstring
  sudo apt-get install php7.0-intl php7.0-mcrypt php-imagick php7.0-xml php7.0-zip
  sudo apt-get install php-redis

+ Nextcloud
  wget https://download.nextcloud.com/server/releases/nextcloud-12.0.4.tar.bz2
  tar -xjf nextcloud-12.0.4.tar.bz2 
  sudo cp -r nextcloud /var/www
  sudo chown -R www-data:www-data /var/www/nextcloud/
  sudo nano /etc/apache2/sites-available/nextcloud.conf
  sudo ln -s /etc/apache2/sites-available/nextcloud.conf /etc/apache2/sites-enabled/nextcloud.conf
    siehe Nextcloud Installationsanleitung
  sudo a2enmod rewrite
  sudo a2enmod headers
  sudo a2enmod env
  sudo a2enmod dir
  sudo a2enmod mime
  sudo service apache2 restart

+ MariaDB Benutzer mit Passwort
  sudo mysql -u root
    FLUSH PRIVILEGES;
    select user,host,password,plugin from mysql.user;
    CREATE USER 'pcadmin'@'localhost' IDENTIFIED BY '...';
    GRANT ALL PRIVILEGES ON *.* TO 'pcadmin'@'localhost' WITH GRANT OPTION;
      delete from mysql.user where user='pcadmin';

+ MariaDB PHPmyAdmin
  sudo apt-get install phpmyadmin php-mbstring php-gettext
  http://localhost/phpmyadmin ==> pcadmin / ...

+ Nextant
  sudo apt-get install default-jre
    an dieser Stelle mal ausgeführt sudo apt-get update && apt-get upgrade
    sudo reboot
  wget http://mirrors.ircam.fr/pub/apache/lucene/solr/6.6.2/solr-6.6.2.tgz
  tar -zxvf solr-6.6.2.tgz
  sudo nano /opt/solr/server/etc/jetty-http.xml
    <Set name="host"><Property name="jetty.host" default="127.0.0.1" /></Set>  
  sudo /etc/init.d/solr start
  sudo -u solr /opt/solr/bin/solr create -c nextant
  http://localhost:8983
  sudo -u www-data php occ nextant:index

+ Docker
  https://gridscale.io/community/tutorials/docker-ubuntu/
  apt-get install curl
  curl https://get.docker.com | bash
  systemctl status docker
  /var/www/nextcloud.../redis
    sudo docker build -t nextcloud/redis .
  /var/www/nextcloud.../worker
  sudo docker build -t nextcloud/ocr .

+ Docker
docker network create --driver bridge isolated_ocr
docker run --name redis --network=isolated_ocr -p 6379:6379 -d ncmap/redis
docker run --name ocr --network=isolated_ocr -e "NODE_ENV=production" -e "REDIS_HOST=redis" -e "REDIS_PORT=6379" -e "REDIS_DB=0" -v /var/www/nextcloud/data:/home/node/data:ro -v /home/pcadmin/nextcloudtemp:/home/node/output -d ncmap/ocr

+ Texterkennung
  tar -zxvf ocr.v3.1.0-beta.1.tar.gz

## Your Environment

* OCR version used: 3.1.0-beta.1
* Browser Name and version: Firefox + Edge
* Operating System and version (desktop or mobile): Windows 10 (PC)
* ownCloud/nextcloud version: (see ownCloud admin page or version.php) 12.04
* PHP version 7.022
* Database version Art: mariadb / mysql Version: 10.0.31 Größe: 2.1 MB
* Are you using encryption: yes/no - no

## Log File Content (nextcloud/owncloud.log of the "data"-directory)

sudo tail /var/www/nextcloud/data/nextcloud.log
{"reqId":"0fFzvxN4iRjZwYULGLGs","level":0,"time":"2017-12-22T15:16:56+00:00","remoteAddr":"192.168.2.36","user":"--","app":"cron","method":"GET","url":"\/nextcloud\/cron.php","message":"Invalidating session tokens older than 2017-12-21T15:16:56+00:00","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"0fFzvxN4iRjZwYULGLGs","level":0,"time":"2017-12-22T15:16:56+00:00","remoteAddr":"192.168.2.36","user":"--","app":"cron","method":"GET","url":"\/nextcloud\/cron.php","message":"Invalidating remembered session tokens older than 2017-12-07T15:16:56+00:00","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"0fFzvxN4iRjZwYULGLGs","level":0,"time":"2017-12-22T15:16:56+00:00","remoteAddr":"192.168.2.36","user":"--","app":"cron","method":"GET","url":"\/nextcloud\/cron.php","message":"Finished OC\\Authentication\\Token\\DefaultTokenCleanupJob job with ID 15 in 0 seconds","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"5CE2blr7stO7sJuHvGBA","level":0,"time":"2017-12-22T15:38:05+00:00","remoteAddr":"192.168.2.36","user":"--","app":"cron","method":"GET","url":"\/nextcloud\/cron.php","message":"Run OCA\\Files_Trashbin\\BackgroundJob\\ExpireTrash job with ID 2","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"5CE2blr7stO7sJuHvGBA","level":0,"time":"2017-12-22T15:38:05+00:00","remoteAddr":"192.168.2.36","user":"--","app":"cron","method":"GET","url":"\/nextcloud\/cron.php","message":"Finished OCA\\Files_Trashbin\\BackgroundJob\\ExpireTrash job with ID 2 in 0 seconds","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"UwKa41aYEs8yv0alMf4P","level":0,"time":"2017-12-22T15:38:14+00:00","remoteAddr":"192.168.2.36","user":"--","app":"cron","method":"GET","url":"\/nextcloud\/cron.php","message":"Run OCA\\Files_Sharing\\DeleteOrphanedSharesJob job with ID 3","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"UwKa41aYEs8yv0alMf4P","level":0,"time":"2017-12-22T15:38:14+00:00","remoteAddr":"192.168.2.36","user":"--","app":"DeleteOrphanedSharesJob","method":"GET","url":"\/nextcloud\/cron.php","message":"0 orphaned share(s) deleted","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"UwKa41aYEs8yv0alMf4P","level":0,"time":"2017-12-22T15:38:14+00:00","remoteAddr":"192.168.2.36","user":"--","app":"cron","method":"GET","url":"\/nextcloud\/cron.php","message":"Finished OCA\\Files_Sharing\\DeleteOrphanedSharesJob job with ID 3 in 0 seconds","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"GlzomHbhS2kH3ZuOtGk0","level":0,"time":"2017-12-22T15:40:07+00:00","remoteAddr":"192.168.2.36","user":"--","app":"cron","method":"GET","url":"\/nextcloud\/cron.php","message":"Run OCA\\Nextant\\Cron\\BackgroundIndex job with ID 17","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"GlzomHbhS2kH3ZuOtGk0","level":0,"time":"2017-12-22T15:40:07+00:00","remoteAddr":"192.168.2.36","user":"--","app":"cron","method":"GET","url":"\/nextcloud\/cron.php","message":"Finished OCA\\Nextant\\Cron\\BackgroundIndex job with ID 17 in 0 seconds","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
pcadmin@nextcloud:~$ sudo tail /var/www/nextcloud/data/nextcloud.log
{"reqId":"GlzomHbhS2kH3ZuOtGk0","level":0,"time":"2017-12-22T15:40:07+00:00","remoteAddr":"192.168.2.36","user":"--","app":"cron","method":"GET","url":"\/nextcloud\/cron.php","message":"Finished OCA\\Nextant\\Cron\\BackgroundIndex job with ID 17 in 0 seconds","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"rfq5vbwj44gp20Ljcxp7","level":0,"time":"2017-12-22T15:44:17+00:00","remoteAddr":"192.168.2.36","user":"--","app":"cron","method":"GET","url":"\/nextcloud\/cron.php","message":"Run OCA\\Files\\BackgroundJob\\ScanFiles job with ID 6","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"rfq5vbwj44gp20Ljcxp7","level":0,"time":"2017-12-22T15:44:17+00:00","remoteAddr":"192.168.2.36","user":"--","app":"cron","method":"GET","url":"\/nextcloud\/cron.php","message":"Finished OCA\\Files\\BackgroundJob\\ScanFiles job with ID 6 in 0 seconds","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"Lhspy6eE7T3mYy05jgdb","level":0,"time":"2017-12-22T15:44:19+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Retrieved the following array from Redis: []","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"Lhspy6eE7T3mYy05jgdb","level":0,"time":"2017-12-22T15:44:19+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Check if files were processed by ocr and if so, put them to the right dirs.","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"Lhspy6eE7T3mYy05jgdb","level":0,"time":"2017-12-22T15:44:19+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Following jobs failed: []","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"7EmzOSdLjqKFmiAdIidb","level":0,"time":"2017-12-22T15:44:41+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"POST","url":"\/nextcloud\/index.php\/apps\/ocr","message":"Will now process files: [{\"id\":\"113\"}] with languages: [\"deu\"] and replace: false","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"aM3RmJt5iFixEX8yLpOT","level":0,"time":"2017-12-22T15:44:46+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Retrieved the following array from Redis: []","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"aM3RmJt5iFixEX8yLpOT","level":0,"time":"2017-12-22T15:44:46+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Check if files were processed by ocr and if so, put them to the right dirs.","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"aM3RmJt5iFixEX8yLpOT","level":0,"time":"2017-12-22T15:44:46+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Following jobs failed: []","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
pcadmin@nextcloud:~$ sudo tail /var/www/nextcloud/data/nextcloud.log
{"reqId":"OBfrnpYKZRCXbl6gNPvA","level":0,"time":"2017-12-22T15:44:55+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Following jobs failed: []","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"DelGvSVId783PTFlqP6U","level":0,"time":"2017-12-22T15:45:00+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Retrieved the following array from Redis: []","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"DelGvSVId783PTFlqP6U","level":0,"time":"2017-12-22T15:45:00+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Check if files were processed by ocr and if so, put them to the right dirs.","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"DelGvSVId783PTFlqP6U","level":0,"time":"2017-12-22T15:45:00+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Following jobs failed: []","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"NTKOFS62baXbwZn1E31x","level":0,"time":"2017-12-22T15:45:04+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Retrieved the following array from Redis: []","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"NTKOFS62baXbwZn1E31x","level":0,"time":"2017-12-22T15:45:04+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Check if files were processed by ocr and if so, put them to the right dirs.","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"NTKOFS62baXbwZn1E31x","level":0,"time":"2017-12-22T15:45:04+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Following jobs failed: []","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"AYDwu2QIrXQPa9R92t0H","level":0,"time":"2017-12-22T15:45:09+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Retrieved the following array from Redis: []","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"AYDwu2QIrXQPa9R92t0H","level":0,"time":"2017-12-22T15:45:09+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Check if files were processed by ocr and if so, put them to the right dirs.","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"AYDwu2QIrXQPa9R92t0H","level":0,"time":"2017-12-22T15:45:09+00:00","remoteAddr":"192.168.2.36","user":"pcadmin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/ocr\/status","message":"Following jobs failed: []","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}

**Comment by seimsel** [comment] 2017-12-26 12:30
Duplicate of #129

**Comment by janis91** [comment] 2017-12-26 18:52
like @seimsel already mentioned. this is a duplicate of #129 and will be therfore closed.

**Closed by janis91** 2017-12-26 18:52 UTC
