### ISSUE TITLE
Can I use the same redis docker I have for NC File Locking for OCR as well?

### ISSUE THREAD

**Issue by mannp** [janis91/ocr#153] opened 2018-03-31 13:55 UTC
I have NC13 setup for redis file locking support and it works well.

I wanted to use the same docker for OCR as well to save resources, is this possible?

Thanks

**Comment by janis91** [comment] 2018-04-01 07:19
I guess yes, but I would recommend to use another database for it. I am not completely sure if there are some critical points, because I didn't try it by myself yet, but I think it should work.

**Comment by mannp** [comment] 2018-04-01 13:54
Ok thanks for the feedback :)

**Comment by mrnoisytiger** [comment] 2018-04-01 22:13
I'm trying to do this setup as well. I have Redis already on the localhost, but I'm having some trouble getting the files to process after somewhat following the installation instructions. I'm skipped building and running the Redis docker, and ran the build command for the OCR docker. To run the OCR worker docker, I ran as root:

    docker run --name ocr -e "NODE_END=production" -e "REDIS_HOST=127.0.0.1" -e "REDIS_PORT=6379" -e "REDIS_DB=15" -v /path:/home/node/data:ro -v /path:/home/node/output -d <user>/ocr

The docker started up without any errors. I went to the admin settings page, and added the following setting:
Installed Languages: eng;spa;deu
Redis Host: 127.0.0.1
Redis Port: 6379
Redis Database: 15
Redis Password: <left blank>

I know my Redis installation does not currently have a password on it, because when I run "redis-cli" and try to auth, it says that no password is set. 

However, when I try to run an OCR on a JPG, the file never makes it past the Pending stage. Any luck setting this up?

**Comment by janis91** [comment] 2018-04-09 09:09
@mrnoisytiger I will have to test it by myself. I cannot definitely say, if I implemented it with the option of "no password" in mind. Maybe this is the root cause. I will try it as soon as possible and if this is not an option maybe even change the source code to add this option.

**Comment by janis91** [comment] 2019-05-26 15:52
I won't support anything prior version 4, because the whole setup is just too much effort. I will close this issue now and hope that version 4 (which will be shipped in a few weeks probably) will fill your need. If not. please feel free to fork the repo and work on the old code base which will reside in the branch "not-maintained".

**Closed by janis91** 2019-05-26 15:52 UTC
