### ISSUE TITLE
PHP error during install: Array to string conversion

### ISSUE THREAD

**Issue by louis77** [janis91/ocr#34] opened 2016-12-21 09:38 UTC
# Bug report
## Expected Behavior

I'm trying to install the OCR app on a Nextcloud 11.0.0 installation with PHP 7.0. 
Tesseract and Ocrmypdf commands are installed and executable for any user:

```
% which ocrmypdf
/usr/local/bin/ocrmypdf
% ls -l /usr/local/bin/ocrmypdf
-rwxr-xr-x  1 root  wheel  242 Dec 20 19:53 /usr/local/bin/ocrmypdf

% which tesseract
/usr/local/bin/tesseract
% ls -l /usr/local/bin/tesseract
-rwxr-xr-x  1 root  wheel  21280 Dec 15 01:42 /usr/local/bin/tesseract
```

## Current Behavior

When I click "Activate" in the Nextcloud App Admin, I get the following error message:

> App "Array" cannot be installed because the following dependencies are not fulfilled: The command line tool ocrmypdf could not be found The command line tool tesseract could not be found

In the Admin/Logging section I can then see two error messages:

> Error	PHP	Array to string conversion at /next/data/nextcloud/lib/private/legacy/l10n/string.php#72

>Error	core	App "Array" cannot be installed because the following dependencies are not fulfilled: The command line tool ocrmypdf could not be found The command line tool tesseract could not be found

## Environment

- Nextcloud 11.0.0
- Postgres 9.3
- PHP 7.0
- FreeBSD 11-stable
- Ocrmypdf 4.3.4
- Local Encryption turned off
```
tesseract 3.04.01
 leptonica-1.72
  libgif 5.1.3 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.6.23+apng : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.5.0 : libopenjp2 2.1.0
```

## Log File Content (nextcloud/owncloud.log of the "data"-directory)

```
{"reqId":"wRghPv69b1oS1OA4rmt7","remoteAddr":"x.x.x.x","app":"PHP","message":"Array to string conversion at \/next\/data\/nextcloud\/lib\/private\/legacy\/l10n\/string.php#72","level":3,"time":"2016-12-21T09:35:48+00:00","method":"POST","url":"\/nextcloud\/index.php\/settings\/ajax\/enableapp.php","user":"x","version":"11.0.0.10"}

{"reqId":"wRghPv69b1oS1OA4rmt7","remoteAddr":"x.x.x.x","app":"core","message":"App \"Array\" cannot be installed because the following dependencies are not fulfilled: The command line tool ocrmypdf could not be found\nThe command line tool tesseract could not be found","level":3,"time":"2016-12-21T09:35:48+00:00","method":"POST","url":"\/nextcloud\/index.php\/settings\/ajax\/enableapp.php","user":"x","version":"11.0.0.10"}
```

**Comment by janis91** [comment] 2016-12-29 19:55
I will come back to this isuue as soon as I can - probably next week. Sorry for the late answer.

**Comment by janis91** [comment] 2017-01-05 14:19
I cannot reproduce this error. for me it works with NC11 from git AND with the prebuilt package from the nextcloud download page. Moreover I tried with the manual installation of the ocr app and the automatic from the appstore. both is working for me. Maybe there is something wrong with FreeBSD in this case. I dont know. Sorry

**Comment by janis91** [comment] 2017-01-20 06:41
Hopefully is fixed now, as the name of the app will stay "ocr" in all languages and is now reduced to only one "name" tag in the appinfo.xml.

**Closed by janis91** 2017-01-20 06:41 UTC
Labels: help wanted

**Comment by akeilox** [comment] 2017-01-22 17:34
I just ran the latest automated script from https://github.com/nextcloud/vm
on a vanilla ubuntu 16.04 x64 

setup other apps fine, nextcloud running fine, but

when attempt to install the OCR app and it gave the same error;

App "OCR" cannot be installed because the following dependencies are not fulfilled: The command line tool ocrmypdf could not be found The command line tool tesseract could not be found

**Comment by janis91** [comment] 2017-01-23 21:06
Do you have the dependencies available in the vm?

**Comment by akeilox** [comment] 2017-01-30 18:18
Sorry for the late reply, yes I had the dependencies available in the vm but it seems some were missing.
Re-run as per https://github.com/jbarlow83/OCRmyPDF/blob/master/docs/installation.rst and i can get ocrmypdf command work now.

Not sure if its indexing, is there a log i can check what its doing in the background?

Another important question is about the External Storage, I have External Storage folder CAMERA added to NextCloud, which is an FTP connection, and contains lots of images.
Will this package attempt to work on all External Storage images? If yes, is there a flag file that I can put somewhere to skip attempt to index them?

Cheers

**Comment by janis91** [comment] 2017-01-31 06:52
This app isn't indexing. It doesn't provide a search or something like that. It's just using ocrmypdf and tesseract-ocr in the background in order to process images and pdf files and get the characters recognized for example from scanned documents.
I didn't setup an external storage before and actually I am not quite sure if this will work.

If you set the debug level to "debug" the app will log to the "owncloud/nextcloud.log" and give some insides.

If you are looking for a search, which as far as I know supports external storage as well, go for https://apps.nextcloud.com/apps/nextant

Cheers

**Comment by erdelyijanos** [comment] 2017-04-01 21:50
I have the exact same issue. (Nextcloud 11.0.2, Ubuntu 16.04, nginx, php7.0)
I played around in the info.xml with "command" dependencies. If I replace tesseract/ocrmypdf with any other common command (like "grep" or "ls") it still says "command line tool grep cannot be found"
If I delete those two lines the app can be enabled but then it really brokes the whole nextcloud.

**Comment by gdgeorge** [comment] 2017-04-05 19:58
Same issue using the ocrmypdf-tess4 docker image and an aliased command (i.e ocrmypdf='docker run --rm -v "$(pwd):/home/docker" ocrmypdf'). The command seems to work from the CLI.
