### ISSUE TITLE
cant find /home/node ... file

### ISSUE THREAD

**Issue by Happyfeet01** [janis91/ocr#118] opened 2017-08-20 13:48 UTC
Hello,

I setup the Docker Container with this command and ocr can connect to the redis Container .

My Data Directory of my nextcloud is /mnt/data 
The tmp dir is /var/www/vhosts/domain/tmp
What is tue correct config? 

```
docker run --name ocr --network=isolated_ocr -e "NODE_ENV=production" -e "REDIS_HOST=redis" -e "REDIS_PORT=6379" -e "REDIS_DB=0" -e "REDIS_PASSWORD=<secret-,pw>" -v /mnt/data:/var/www/vhosts/domain.tld/node/data:ro -v /var/www/vhosts/domain.tld/tmp:/var/www/vhosts/domain.tld/node/output -d user/ocr
```

Now i get this message at the ocr Docker Container:

error: Job errored: The execution of 'ocrmypdf' command failed: ERROR - File not found - /home/node/data/lars/files/Arbeitsrecht.pdf

**Comment by janis91** [comment] 2017-08-22 18:51
I think you got the binding of the directories wrong. Basically you connect your data/tmp directory to the internal directory (which is used by the worker inside of the docker container).
Therefore you take your data dir in fornt of `:/home/node/data:ro` like so:
`-v /mnt/data:/home/node/data:ro`
And for the tmp dir you do like the following:
`-v /var/www/vhosts/domain/tmp:/home/node/output`

This is basically it.

**Comment by Happyfeet01** [comment] 2017-08-26 14:23
Okay once again.

It won't work.
I use this setup:
```
docker build --build-arg PASSWORD="password" -t lars/redis .
```

```
docker run --name ocr --network=isolated_ocr -e "NODE_ENV=production" -e "REDIS_HOST=redis" -e "REDIS_PORT=6379" -e "REDIS_DB=0" -e "REDIS_PASSWORD=password" -v /mnt/data:/home/node/data:ro -v /var/www/vhosts/larsmueller.net/tmp:/home/node/output -d lars/ocr
```

Redis log: 

```
1:C 26 Aug 13:26:06.693 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 26 Aug 13:26:06.693 # Redis version=4.0.1, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 26 Aug 13:26:06.693 # Configuration loaded
1:M 26 Aug 13:26:06.695 * Running mode=standalone, port=6379.
1:M 26 Aug 13:26:06.695 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 26 Aug 13:26:06.695 # Server initialized
1:M 26 Aug 13:26:06.696 * Ready to accept connections
1:M 26 Aug 13:31:07.078 * 10 changes in 300 seconds. Saving...
1:M 26 Aug 13:31:07.079 * Background saving started by pid 17
17:C 26 Aug 13:31:07.178 * DB saved on disk
17:C 26 Aug 13:31:07.179 * RDB: 0 MB of memory used by copy-on-write
1:M 26 Aug 13:31:07.179 * Background saving terminated with success
1:M 26 Aug 13:36:08.088 * 10 changes in 300 seconds. Saving...
1:M 26 Aug 13:36:08.088 * Background saving started by pid 18
18:C 26 Aug 13:36:08.168 * DB saved on disk
18:C 26 Aug 13:36:08.169 * RDB: 0 MB of memory used by copy-on-write
1:M 26 Aug 13:36:08.189 * Background saving terminated with success
1:M 26 Aug 13:45:01.454 * 10 changes in 300 seconds. Saving...
1:M 26 Aug 13:45:01.455 * Background saving started by pid 19
19:C 26 Aug 13:45:01.537 * DB saved on disk
19:C 26 Aug 13:45:01.538 * RDB: 0 MB of memory used by copy-on-write
1:M 26 Aug 13:45:01.555 * Background saving terminated with success
1:M 26 Aug 13:50:02.060 * 10 changes in 300 seconds. Saving...
1:M 26 Aug 13:50:02.061 * Background saving started by pid 20
20:C 26 Aug 13:50:02.172 * DB saved on disk
20:C 26 Aug 13:50:02.173 * RDB: 0 MB of memory used by copy-on-write
1:M 26 Aug 13:50:02.262 * Background saving terminated with success
1:M 26 Aug 14:00:02.094 * 10 changes in 300 seconds. Saving...
1:M 26 Aug 14:00:02.094 * Background saving started by pid 21
21:C 26 Aug 14:00:02.374 * DB saved on disk
21:C 26 Aug 14:00:02.375 * RDB: 0 MB of memory used by copy-on-write
1:M 26 Aug 14:00:02.394 * Background saving terminated with success
1:M 26 Aug 14:05:03.009 * 10 changes in 300 seconds. Saving...
1:M 26 Aug 14:05:03.010 * Background saving started by pid 33
33:C 26 Aug 14:05:03.178 * DB saved on disk
33:C 26 Aug 14:05:03.179 * RDB: 0 MB of memory used by copy-on-write
1:M 26 Aug 14:05:03.210 * Background saving terminated with success
1:M 26 Aug 14:15:01.335 * 10 changes in 300 seconds. Saving...
1:M 26 Aug 14:15:01.335 * Background saving started by pid 176
176:C 26 Aug 14:15:01.475 * DB saved on disk
176:C 26 Aug 14:15:01.476 * RDB: 0 MB of memory used by copy-on-write
1:M 26 Aug 14:15:01.537 * Background saving terminated with success
```

OCR

```
2017-08-26T13:26:04.810Z - error: ERROR: getaddrinfo ENOTFOUND redis redis:6379.
2017-08-26T13:26:04.810Z - warn: Connection closed to redis server.
2017-08-26T13:31:01.518Z - error: Job errored: The execution of 'ocrmypdf' command failed: ERROR - File not found - /home/node/data/lars/files/Clatronic_user_manual_MWG_775_H.pdf
```

What is wrong?

**Comment by Happyfeet01** [comment] 2017-08-27 08:34
Okay today next try.

`I delete the OCR Container and setup it again with docker run --name ocr --network=isolated_ocr -e "NODE_ENV=production" -e "REDIS_HOST=redis" -e "REDIS_PORT=6379" -e "REDIS_DB=0"  -v /mnt/data:/home/node/data:ro -v /var/www/vhosts/larsmueller.net/tmp:/home/node/output -d lars/ocr
`
i get this Warning and Error Message:

`2017-08-27T08:23:28.202Z - error: ERROR: NOAUTH Authentication required..
2017-08-27T08:23:28.203Z - warn: Connection closed to redis server.`

so add an password option to start the container:

`docker run --name ocr --network=isolated_ocr -e "NODE_ENV=production" -e "REDIS_HOST=redis" -e "REDIS_PORT=6379" -e "REDIS_DB=0" -e "REDIS_PASSWORD=supersavepassword" -v /mnt/data:/home/node/data:ro -v /var/www/vhosts/larsmueller.net/tmp:/home/node/output -d lars/ocr
`
and i get this message:

`2017-08-27T08:26:44.681Z - error: Job errored: The execution of 'ocrmypdf' command failed: ERROR - File not found - /home/node/data/lars/files/Dokumente/Banking4A.Handbuch.pdf
`
what is wrong with the Setup?

**Comment by janis91** [comment] 2017-08-27 12:17
Are your files really in /mnt/data? I mean is the Banking4A.Handbuch.pdf located under:
``/mnt/data/lars/files/Dokumente/Banking4A.Handbuch.pdf``
?

**Comment by Happyfeet01** [comment] 2017-08-27 12:54
Yes that is the real data folder

**Comment by janis91** [comment] 2017-08-27 13:07
does your docker user have normal rights? I mean I cannot see any mistake from here. I mean you could try if mounting the data directory to the docker container worked, by using "docker container exec". Try to fetch the directory content of your ``/home/node/data`` then. If there is nothing inside of this folder, there seems to be a problem with mounting your local data dir to your docker container's data dir.

**Comment by Happyfeet01** [comment] 2017-08-27 13:19
```
docker exec a7bbab3a6fd2  /home/node/data
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"/home/node/data\": permission denied"
```
```
root@h2622464:~# docker exec -it a7bbab3a6fd2 bash
node@a7bbab3a6fd2:~/worker$ cd /home/node/data
bash: cd: /home/node/data: Permission denied
node@a7bbab3a6fd2:~/worker$ cd /home/node
node@a7bbab3a6fd2:~$ ls
data  output  worker
node@a7bbab3a6fd2:~$ ls -la
total 32
drwxr-xr-x  5 node  node 4096 Aug 20 06:41 .
drwxr-xr-x  3 root  root 4096 Aug 20 06:41 ..
-rw-r--r-- 10 node  node  220 Jun 24  2016 .bash_logout
-rw-r--r-- 10 node  node 3771 Jun 24  2016 .bashrc
-rw-r--r-- 10 node  node  655 Jun 24  2016 .profile
drwxr-x--- 23 10000 1003 4096 Aug 18 18:13 data
drwxr-xr-x  2 root  root 4096 Aug 20 12:25 output
drwxr-xr-x  4 root  root 4096 Aug 20 06:42 worker
node@a7bbab3a6fd2:~$
```

**Comment by janis91** [comment] 2017-08-27 14:40
maybe this is a possible cause of this. But I don't know how to configure it right..

**Comment by Happyfeet01** [comment] 2017-08-27 15:29
and when i change this `/home/node/data:ro` to `/home/node/data:rw`

**Comment by janis91** [comment] 2017-08-28 05:14
Is it working then?

**Comment by Happyfeet01** [comment] 2017-08-28 08:55
Yes the docker user was created when I install the docker package. The Nextcloud  www User has sudo rights.

**Comment by janis91** [comment] 2017-08-28 10:39
Well even if it is workong when you give it the right to write, it shouldn't at least be necessary to do so. The data folder is only used to read. And for that I used to be as restricted as possible.. btw sou should never give root permissions to the server user. But I think this is definetely not possible to solve by me. Maybe you should adapt some permissions that it fits, but as i said before: never give sudo to the server.
I will close this ticket, as it is not really possible for me to solve this issue mainly because it is not caused by this app.

**Closed by janis91** 2017-08-28 10:39 UTC

**Comment by Happyfeet01** [comment] 2018-04-02 15:18
Hello again,

i try it again. The Symlink from /mnt/data/lars:/home/node/ already exist and is correct. (I See the data folder and the entrys).

What is wrong here? 

My current setup: 

- nextcloud 13
latest ocr app

```

docker run --name redis --network=isolated_ocr -p 6381:6381 -d nccloud/redis
```
```
docker run --name ocr --network=isolated_ocr -e "NODE_ENV=production" -e "REDIS_HOST=redis" -e "REDIS_PORT=6381" -e "REDIS_DB=0" -e "REDIS_PASSWORD=Ji8D92U3" -v /var/www/vhosts/domain/ncdata/data/lars/files:/home/node/data:ro -v /var/www/vhosts/domain/tmp:/home/node/output -d nccloud/ocr
```
